language: swift
osx_image: xcode10.0

branches:
  only:
  - master
  - /^v.*$/
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild -workspace NulpAppApi.xcworkspace -scheme NulpAppApi -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
deploy:
  provider: releases
  api_key: "$Git_key"
  file : /Users/travis/Library/Developer/Xcode/DerivedData/NulpAppApi-fztiiouihfuodtbppihzphudsdif/Build/Products/Debug-iphonesimulator/NulpAppApi.app
  skip_cleanup: true
  on:
     tags: false
     all_branches: true
