language: swift
osx_image: xcode10.0

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild -workspace NulpAppApi.xcworkspace -scheme NulpAppApi -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
before_deploy:
  - git config --local user.name "Agipas"
  - git config --local user.email "ivansapiga1999@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  api_key: '$GITKEY'
  git : NulpAppApi.xcodeproj
  skip_cleanup: true
  on:
     tags: true
     all_branches: true
